# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(blank=True, choices=[('NOT_DONE', 'Not done'), ('WAITING_FOR_CONFIRMATION', 'Waiting for confirmation'), ('SUCCESSFUL', 'Successful')], default='NOT_DONE', max_length=20)),
            ],
        ),
    ]
