# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='activities.Booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='users',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='activity_registration',
        ),
        migrations.AddField(
            model_name='activity',
            name='max_bookings_per_day',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='rules_of_security',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_DONE', 'Not done'), ('WAITING_FOR_CONFIRMATION', 'Waiting for confirmation'), ('SUCCESSFUL', 'Successful')], default='NOT_DONE', max_length=20),
        ),
        migrations.DeleteModel(
            name='ActivityRegistration',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='activities.Activity'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.Payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
    ]
