# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20170729_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='stuff_to_bring',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
