# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_stuff_to_bring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='stuff_to_bring',
        ),
        migrations.AddField(
            model_name='activity',
            name='stuff_to_take',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
