# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20170729_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='background',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='logo',
        ),
        migrations.AddField(
            model_name='activity',
            name='background_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
