# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20170730_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregistration',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='payments.Payment'),
        ),
    ]
