# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_sportrotteruser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.FileField(upload_to='backgrounds')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('diploma', models.FileField(upload_to='diplomas')),
                ('grade', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('AMATEUR', 'Amateur'), ('PROFESSIONAL', 'Professional')], default='AMATEUR', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='sportrotteruser',
            name='professional',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.Professional'),
        ),
    ]
