# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170729_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportrotteruser',
            name='professional',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.Professional'),
        ),
    ]
