# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170729_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='gallery')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='authentication.Professional')),
            ],
        ),
    ]
