# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170729_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='background',
        ),
        migrations.RemoveField(
            model_name='sportrotteruser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='background_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sportrotteruser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
