# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 10:15
from __future__ import unicode_literals

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20170730_0922'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sportrotteruser',
            managers=[
                ('objects', authentication.models.Manager()),
            ],
        ),
    ]
